steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/storied-shelter-430907-c9{cloudbuild1}:${SHORT_SHA}', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/storied-shelter-430907-c9{cloudbuild1}:${SHORT_SHA}']
  id: Pushing the image to registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${cloudbuild1}', '--image', 'gcr.io/storied-shelter-430907-c9{cloudbuild1}:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', "--allow-unauthenticated"]

  options:
    logging:  'CLOUD_LOGGING_ONLY'
